### ISSUE TITLE
Watch mode issues

### ISSUE THREAD

**Issue by karolis-sh** [waspeer/esbuild-plugin-glob#1]
Thanks for this helpful abstraction, though I noticed some issues with updating and deleting entry files in watch mode - they don't affect the output changes.

File deletion doesn't work because the `write` seems to be true by default https://esbuild.github.io/api/#write (https://github.com/waspeer/esbuild-plugin-glob/blob/main/src/index.ts#L122 and this check for the value in the config)

File watcher doesn't work because of the faulty `normalizePath` function https://github.com/waspeer/esbuild-plugin-glob/blob/main/src/index.ts#L147. Here the `__dirname` is actually the node modules directory. When this function gets called `normalizePath('src/index.js')` returns something like `../../../src/index.js`, you should use something like `process.cwd()`.

**Comment by waspeer** [comment]
Hey! Thanks for making this issue.

I clearly have left in some logic in there that only made sense during development. I kinda just ripped it out of a project I was working on and published it. Thank for pointing this out!

I already pushed a new version that normalizes the paths from `process.cwd()` and started on writing tests. I'm hoping to finish these this week.

**Comment by waspeer** [comment]
I added tests + fixed the file deletion issue. These issues should be fixed when you update!
