### ISSUE TITLE
Files included that should be ignored

### ISSUE THREAD

**Issue by Fdawgs** [waspeer/esbuild-plugin-glob#15]
Hi there!

When using this plugin, it appears nested files that should be ignored by glob "not patterns" are still included.

Example app structure:
```
/src/app.js
/src/app.test.js
/src/route/example.js
/src/route/example.test.js
```

Example build script:
```js
const { build } = require("esbuild");
const { globPlugin } = require("esbuild-plugin-glob");

build({
	entryPoints: ["src/**/!(*.test).js"],
	format: "cjs",
	minify: true,
	outdir: "dist",
	platform: "node",
	plugins: [globPlugin()],
	target: "node14",
}).catch(() => process.exit(1));
```

When executing the above build script, it creates the following outdir structure:
```
/dist/app.js
/dist/route/example.js
/dist/route/example.test.js
```
The top level `.test.js` file is excluded but not the nested `.test.js` file.

### Potential cause

From playing around with glob modules in an attempt to diagnose this, it seems that `tiny-glob` is the issue.

The following example, using the `glob` dependency, will remove all JS files besides test files (as expected):
```js
const glob = require("glob");
const files = glob.sync("dist/**/!(*.test).js");
await Promise.all(files.map((file) => fs.unlink(file)));
```
The following, using `tiny-glob`, removes every JS file apart from a top level test file, instead of only removing test files:
```js
const glob = require("tiny-glob");
const files = await glob("dist/**/!(*.test).js");
await Promise.all(files.map((file) => fs.unlink(file)));
```

**Comment by waspeer** [comment]
Hey @Fdawgs,
Thanks for this well-researched issue! I'll look into switching to `glob` instead of `tiny-glob` today. Seems like not to big of change to solve this issue.

**Comment by waspeer** [comment]
I've created a pr for this change and added tests based on your example. I haven't been able to replicate the issue though. Would you be able to take a look to see if I missed anything? I know the tests are a bit complex, let me know if you need more information about what's going on there.

**Comment by Fdawgs** [comment]
Great @waspeer, thanks!
I'm on holiday atm but should be able to test when back on 17th.

**Comment by waspeer** [comment]
Oh wait, I'm just now seeing that this test failed in the matrix tests on node 16 on windows. Is that by any chance what you're rocking? I'm on node 16 on mac atm. Platform differences might be the cause of this issue.

**Comment by Fdawgs** [comment]
> Oh wait, I'm just now seeing that this test failed in the matrix tests on node 16 on windows. Is that by any chance what you're rocking? I'm on node 16 on mac atm. Platform differences might be the cause of this issue.

Yeah, sorry forgot to state platform in original issue.

Node 16.17.1 on Windows 10.

**Comment by waspeer** [comment]
Should be fixed in the new version!

**Comment by Fdawgs** [comment]
Works a treat, thanks!
