### ISSUE TITLE
Adding a silent option

### ISSUE THREAD

**Issue by PierBover** [waspeer/esbuild-plugin-glob#4]
This plugin is fantastic!

Would it be ok if I did a PR that would add silent option to remove all the outputs to the console?

**Comment by waspeer** [comment]
Thanks @PierBover! :) That would be great

**Comment by waspeer** [comment]
Maybe we should adopt an actual logger to do this? Do you have any in mind?

**Comment by waspeer** [comment]
Yeah on second thought, it's not worth it to add another dependency for it. A simple logger function is probably better. Nvm!

**Comment by waspeer** [comment]
Hi @PierBover ! I had some spare time so I worked on this a bit. Could you check the PR and let me know if this is what you had in mind?

-> https://github.com/waspeer/esbuild-plugin-glob/pull/6

**Comment by PierBover** [comment]
Yeah this is exactly what I had in mind.

Sorry for not following through on this.

**Comment by waspeer** [comment]
No problem at all! Thanks for helping me improve this plugin :) I'll release a new version right away!
