### ISSUE TITLE
Watch mode crashes

### ISSUE THREAD

**Issue by PierBover** [waspeer/esbuild-plugin-glob#9]
It seems `esbuild-plugin-glob` crashes the watch mode.

I first I thought it was the Svelte plugin but I've been able to narrow it down in this repro.

https://github.com/PierBover/esbuild-svelte-error-repro/

To reproduce:

1. `npm run dev`
2. Uncomment [this line](https://github.com/PierBover/esbuild-svelte-error-repro/blob/main/Something.svelte#L2)

 If you remove the glob plugin, watch mode works as expected and EsBuild rebuilds after fixing the error.

**Comment by waspeer** [comment]
Hi @PierBover, thanks for adding this issue.

I've created a pr that should fix this problem. It would be great if you could check if this solution works for you as well.

https://github.com/waspeer/esbuild-plugin-glob/pull/10

**Comment by PierBover** [comment]
Thanks @waspeer !

Is there a way to install the PR from NPM?

**Comment by waspeer** [comment]
You could clone the branch and use npm link or run this command:

```sh
npm i git://github.com/waspeer/esbuild-plugin-glob.git#dont-crash
```

**Comment by waspeer** [comment]
I'm going to merge this next week, lmk if there's something that could be improved.

**Comment by coreymcollins** [comment]
Do you still have plans to merge this PR in?

**Comment by waspeer** [comment]
Hi @coreymcollins, thanks for reminding me! :) I just merged this change and released a new version. Lmk if this resolves your issues.
